#Digunakan jika ingin mendeploy sebuah pod di setiap node
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{daemon-set-name}}
  labels:
    label-name: {{label-value1}}
spec:
  selector:
    matchLabels:
      label-name: {{label-value1}}
    matchExpressions:
      - key: label-name
        operator: In
        values:
          - label-value1
  template:
    metadata:
      name: {{pod-name}}
      labels:
        label-name: {{label-value1}}
    spec:
      containers:
        - name: {{container-name}}
          image: {{image-name}}
          ports:
            - containerPort: 80