apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ deployment_name }}
  labels:
    app: {{ app_name }}
  annotations:
    description: annotation description . . . .
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ app_name }}
  template:
    metadata:
      labels:
        app: {{ app_name }}
      annotations:
        description: annotation description . . . .
    spec:
      imagePullSecrets:
        - name: {{ secret_registry_name }}
      containers:
      - name: {{ app_name }}
        image: {{ app_image }}
        volumeMounts:
        - mountPath: {{ container_path_dir }}
          name: logs
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        env:
        - name: DB_HOST
          valueFrom: 
            configMapKeyRef:
              name: {{ configmap_name }}
              key: db_host
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ db_secret_name }}
              key: db_password
        readinessProbe:
          failureThreshold: 3 #berapa kali fail sampai pod dinyatakan unhealty
          httpGet:
            path: /healtcheck
            port: 80
            scheme: HTTP
            initialDelayedSeconds: 3 #initial detik saat akan melakukan pengecekan
            periodSeconds: 3 
            successThreshold: 1 #berapa kali success sampai pod dinyatakan ready
          timeoutSeconds: 1 #waktu timeout untuk response
          resources:
            requests:
              # milli core
              cpu: 1000m
              # mebibyte
              memory: 250Mi
            limits:
              # milli core
              cpu: 2000m
              # mebibyte
              memory: 500Mi
      volumes:
      - name: logs
        hostPath:
          path: {{ host_path_dir }}
          type: Directory